version: 2.1

parameters:
  docker-image:
    type: string
    default: "repository.intranet.roche.com:6581/r/rocker/nest:latest"

jobs:
  example:
    docker:
      - image: << pipeline.parameters.docker-image >>
    steps:
      - checkout
      - run:
          name: Print the Current Time
          command: date

workflows:
  version: 2
  build:
    jobs:
      - example
  hourlyscheduled:
    triggers:
      - schedule:
          cron: "0 * * * *"
    jobs:
       - example
