version: 2.1

jobs:
  example:
    docker:
      - image: docker-cache.repository.intranet.roche.com/bash:4.4.19
    steps:
      - run:
          name: Print the Current Time
          command: date

workflows:
  version: 2
  build:
    jobs:
      - example
  hourlyscheduled:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - example
